package com.geoknoesis.kastor.examples.dcat

import com.geoknoesis.kastor.rdf.*
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.*

/**
 * Tests for the DCAT-US OntoMapper example.
 * 
 * These tests demonstrate the generated code functionality
 * and validate that the example works correctly.
 */
class DCAT_US_ExampleTest {
    
    private val example = DCAT_US_Example()
    
    @Test
    fun `should create catalog successfully`() {
        // Given
        // When
        val catalog = example.createCatalogExample()
        
        // Then
        assertNotNull(catalog)
        assertEquals("Example Government Data Catalog", catalog.title)
        assertEquals("A comprehensive catalog of government datasets and services", catalog.description)
        assertNotNull(catalog.publisher)
    }
    
    @Test
    fun `should create dataset successfully`() {
        // Given
        // When
        val dataset = example.createDatasetExample()
        
        // Then
        assertNotNull(dataset)
        assertEquals("Weather Data Collection", dataset.title)
        assertEquals("Daily weather measurements from weather stations across the state", dataset.description)
        assertTrue(dataset.keywords.contains("weather"))
        assertTrue(dataset.keywords.contains("climate"))
        assertNotNull(dataset.publisher)
        assertTrue(dataset.distributions.isNotEmpty())
    }
    
    @Test
    fun `should create distribution successfully`() {
        // Given
        // When
        val distribution = example.createDistributionExample()
        
        // Then
        assertNotNull(distribution)
        assertEquals("Weather Data - CSV Format", distribution.title)
        assertNotNull(distribution.accessUrl)
        assertNotNull(distribution.mediaType)
        assertEquals("text/csv", distribution.mediaType)
        assertNotNull(distribution.format)
    }
    
    @Test
    fun `should create comprehensive catalog with DSL`() {
        // Given
        // When
        val catalog = example.createCatalogWithDsl()
        
        // Then
        assertNotNull(catalog)
        assertEquals("Comprehensive Government Data Catalog", catalog.title)
        assertTrue(catalog.datasets.size >= 2)
        assertTrue(catalog.dataServices.isNotEmpty())
        
        // Verify datasets
        val datasetTitles = catalog.datasets.map { it.title }
        assertTrue(datasetTitles.contains("Population Statistics"))
        assertTrue(datasetTitles.contains("Budget Information"))
    }
    
    @Test
    fun `should query catalog data successfully`() {
        // Given
        example.createCatalogExample()
        example.createDatasetExample()
        
        // When
        val datasets = example.queryCatalogData()
        
        // Then
        assertNotNull(datasets)
        assertTrue(datasets.isNotEmpty())
    }
    
    @Test
    fun `should validate catalog data`() {
        // Given
        example.createCatalogExample()
        example.createDatasetExample()
        
        // When
        val validationResult = example.validateCatalogData()
        
        // Then
        assertNotNull(validationResult)
        // Note: Validation result may vary based on implementation
    }
    
    @Test
    fun `should export catalog as JSON-LD`() {
        // Given
        val catalog = example.createCatalogExample()
        
        // When
        val jsonLd = example.exportCatalogAsJsonLd(catalog)
        
        // Then
        assertNotNull(jsonLd)
        assertTrue(jsonLd.isNotEmpty())
        assertTrue(jsonLd.contains("@context"))
        assertTrue(jsonLd.contains("dcat"))
    }
    
    @Test
    fun `should demonstrate vocabulary usage`() {
        // Given
        // When using generated vocabulary (this would be generated by OntoMapper)
        // val catalogUri = Iri("https://data.example.gov/catalog")
        
        // Then
        // This test demonstrates how the generated vocabulary would be used
        // In a real implementation, this would use the generated DCAT_US_Vocabulary object
        
        // Example of what the generated code would look like:
        /*
        val catalog = CatalogBuilder()
            .uri(catalogUri)
            .title("Test Catalog")
            .description("Test Description")
            .publisher(createTestPublisher())
            .build()
        
        assertNotNull(catalog)
        assertEquals("Test Catalog", catalog.title)
        */
        
        // For now, we'll just verify the example structure
        assertTrue(true) // Placeholder assertion
    }
    
    @Test
    fun `should demonstrate SHACL validation`() {
        // Given
        val catalog = example.createCatalogExample()
        val dataset = example.createDatasetExample()
        
        // When
        val validationResult = example.validateCatalogData()
        
        // Then
        assertNotNull(validationResult)
        
        // In a real implementation, this would use generated SHACL validation
        // based on the DCAT-US SHACL shapes
        /*
        val shaclValidator = DCAT_US_ShaclValidator()
        val validationReport = shaclValidator.validate(listOf(catalog, dataset))
        
        assertTrue(validationReport.isValid)
        */
    }
    
    @Test
    fun `should demonstrate serialization formats`() {
        // Given
        val catalog = example.createCatalogExample()
        
        // When
        val jsonLd = example.exportCatalogAsJsonLd(catalog)
        
        // Then
        assertNotNull(jsonLd)
        assertTrue(jsonLd.isNotEmpty())
        
        // Verify JSON-LD structure
        assertTrue(jsonLd.contains("\"@type\""))
        assertTrue(jsonLd.contains("\"dcat:Catalog\""))
        assertTrue(jsonLd.contains("\"dcat:title\""))
    }
    
    // Helper method for creating test publisher
    private fun createTestPublisher(): Agent {
        return AgentBuilder()
            .uri(Iri("https://www.example.gov/agency"))
            .name("Test Government Agency")
            .homepage(Iri("https://www.example.gov"))
            .build()
    }
}









