// DCAT-US Kastor Gen Example
// Code is generated by the Kastor KSP processor (added to every :examples:* project by the root build)
// from src/main/resources/dcat-us_3.0_shacl_shapes.ttl; see DCAT_US_Generated_Example.kt.

plugins {
    id("org.jetbrains.kotlin.jvm")
}

dependencies {
    // Core Kastor dependencies - using project dependencies
    implementation(project(":rdf:core"))
    implementation(project(":kastor-gen:runtime"))
}

// Task to run the example
tasks.register<JavaExec>("run") {
    mainClass.set("com.geoknoesis.kastor.examples.dcat.DCAT_US_ExampleKt")
    classpath = sourceSets.main.get().runtimeClasspath
    description = "Run the DCAT-US Kastor Gen example"
    group = "examples"
}

// Task to run the manual example
tasks.register<JavaExec>("runManualExample") {
    mainClass.set("com.geoknoesis.kastor.examples.dcat.DCAT_US_Manual_ExampleKt")
    classpath = sourceSets.main.get().runtimeClasspath
    description = "Run the hand-written DCAT-US domain-class example"
    group = "examples"
}

// Task to run the generated interfaces example
tasks.register<JavaExec>("runGeneratedExample") {
    mainClass.set("com.geoknoesis.kastor.examples.dcat.DCAT_US_Generated_ExampleKt")
    classpath = sourceSets.main.get().runtimeClasspath
    description = "Run the DCAT-US example using interfaces generated from the SHACL shapes"
    group = "examples"
}
